# Latihan program perhitungan temperature

# program konversi celcius ke satuan lain

# print('\nPROGRAM KONVERSI TEMPERATUR\n')

celcius=float(input('Masukan suhu dalam celcius :'))
print(f'suhu adalah {celcius}celcius')

#reamur
reamur= (4/5)* celcius
print(f'suhu dalam reamur adalah {reamur} Reamur')

#fahrenhait 

fahrenhait =((9/5)*celcius) +32
print(f'suhu dalam fahrenhait adalah {fahrenhait} fahrenhait')

#kelvin

kelvin = celcius +273

print(f'suhu dalam kelvin adalah {kelvin} kelvin')