# OPERATOR ARITMATIKA
# Penjumlahan

from re import A
print(13 +2)
apel = 7
jeruk= 9
buah = apel +jeruk 
print(buah)

#pengurangan
hutang = 1000000
bayar = 500000
sisaHutang= hutang - bayar
print(f'sisa hutang anda adalah',sisaHutang)

#perkalian
panjang = 15
lebar =8
luas = panjang *lebar
print(luas)

#pembagian
kue = 16
anak = 4
kuePerAnak =kue/anak
print(f'setiap anak akan mendapatkan bagian kue sebanyak :{kuePerAnak}')

#sisa bagi /modulus

bilangan1 = 14
bilangan2 = 5
hasil = bilangan1 % bilangan2
print("Sisa bagi dari bilangan ", bilangan1, " dan ", bilangan2, " adalah ", hasil)

#pangkat
bilangan3 = 8
bilangan4 = 2
hasilPangkat = bilangan3 ** bilangan4
print(hasilPangkat)
#pembagian Bulat
print(10//3)
#10 dibagi 3 adalah 3.3333. Karena dibulatkan maka akan menghasilkan nilai 3